# Generated by Django 2.1.4 on 2019-10-20 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_provided',
            field=models.BooleanField(default=False, help_text='O grupo foi liberado para visualização pelos estudantes.', verbose_name='Foi liberado?'),
        ),
    ]
