# Generated by Django 2.1.4 on 2019-11-03 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_group_is_provided'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='group',
            table='alma_groups',
        ),
    ]
