# Generated by Django 2.1.4 on 2019-11-03 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190928_0212'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='news',
            table='alma_news',
        ),
    ]
