# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
        environment:
          - POSTGRES_DB=vwapp_db
          - POSTGRES_USER=vwapp
          - POSTGRES_PASSWORD=vwapp
          - POSTGRES_HOST=localhost
          - POSTGRES_PORT=5432

      - image: circleci/postgres:9.6.2-alpine
        environment:
          - POSTGRES_PASSWORD=vwapp
          - POSTGRES_USER=vwapp
          - POSTGRES_DB=vwapp_db

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "project/requirements.txt" }}
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r project/requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "project/requirements.txt" }}

      - run:
          name: Flake8
          command: |
            . venv/bin/activate
            flake8 ./project

      - run:
          name: Tests
          command: |
            . venv/bin/activate
            python project/manage.py test ./project