# Generated by Django 2.1.4 on 2019-11-10 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0002_auto_20191103_0319'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='methodology',
            field=models.CharField(choices=[('TRADITIONAL', 'TRADITIONAL'), ('TBL', 'TBL')], default='TRADITIONAL', help_text='Tipo de metodologia ativa de aprendizado ou tradicional.', max_length=50, verbose_name='Tipo de metodologia'),
        ),
    ]
