# Generated by Django 2.1.4 on 2019-11-24 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0003_section_methodology'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data na qual o objeto foi criado.', verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data na qual o objeto foi atualizado.', verbose_name='Atualizado em')),
                ('title', models.CharField(blank=True, help_text='Título da avaliação, por exemplo, iRAT, gRAt e etc...', max_length=100, verbose_name='Título da prova')),
                ('datetime', models.DateTimeField(blank=True, help_text='Data e hora que a prova será disponibilizada para os alunos.', null=True, verbose_name='Dia/hora da prova')),
                ('weight', models.PositiveIntegerField(default=10, help_text='Peso da avaliação de 0 a 10.', verbose_name='Peso da avaliação')),
                ('duration', models.PositiveIntegerField(default=30, help_text='Duração da prova em minutos.', verbose_name='Duração da prova')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_config', to='sections.Section')),
            ],
            options={
                'db_table': 'alma_section_exam_config',
                'ordering': ['created_at'],
            },
        ),
    ]
