# Generated by Django 2.1.4 on 2019-10-26 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data na qual o objeto foi criado.', verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data na qual o objeto foi atualizado.', verbose_name='Atualizado em')),
                ('title', models.CharField(help_text='Título da questão', max_length=50, verbose_name='Título')),
                ('description', models.TextField(help_text='Descrição da seção', verbose_name='Descrição')),
                ('is_exercise', models.BooleanField(default=True, help_text='Verifica se a questão criada é um exercício.', verbose_name='É um exercício?')),
                ('question_type', models.CharField(choices=[('V_OR_F', 'V_OR_F'), ('MULTIPLE_CHOICES', 'MULTIPLE_CHOICES')], default='MULTIPLE_CHOICES', help_text='Tipos de questão que podem ser criadas.', max_length=20, verbose_name='Tipo de questão')),
                ('correct_answer', models.CharField(choices=[('UNDEFINED', 'UNDEFINED'), ('TRUE', 'TRUE'), ('FALSE', 'FALSE'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='UNDEFINED', help_text='Respostas corretas para cada tipo de questão criada.', max_length=20, verbose_name='Resposta correta')),
                ('alternative_A', models.CharField(blank=True, help_text='Descrição da alternativa A', max_length=500, verbose_name='Alternativa A')),
                ('alternative_B', models.CharField(blank=True, help_text='Descrição da alternativa B', max_length=500, verbose_name='Alternativa B')),
                ('alternative_C', models.CharField(blank=True, help_text='Descrição da alternativa C', max_length=500, verbose_name='Alternativa C')),
                ('alternative_D', models.CharField(blank=True, help_text='Descrição da alternativa D', max_length=500, verbose_name='Alternativa D')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='sections.Section')),
            ],
            options={
                'ordering': ['title', 'created_at'],
            },
        ),
    ]
