# Generated by Django 2.1.4 on 2019-11-03 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20191026_2110'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='alternative',
            table='alma_alternatives',
        ),
        migrations.AlterModelTable(
            name='question',
            table='alma_questions',
        ),
    ]
