# Generated by Django 2.1.4 on 2019-11-10 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20191103_0319'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_exam',
            field=models.CharField(blank=True, choices=[('TRADITIONAL', 'TRADITIONAL'), ('TBL', 'TBL')], help_text='Caso não for um exercício, verificar o tipo de exame ele faz parte.', max_length=30, verbose_name='Tipo de exame'),
        ),
    ]
