# Generated by Django 2.1.4 on 2019-11-10 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_auto_20191110_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='exam',
            field=models.CharField(choices=[('EXERCISE', 'EXERCISE'), ('TRADITIONAL', 'TRADITIONAL'), ('TBL', 'TBL')], default='EXERCISE', help_text='Verificar o tipo de exame que a questão irá fazer parte.', max_length=30, verbose_name='Tipo de exame'),
        ),
    ]
