# Generated by Django 2.1.4 on 2019-11-10 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_auto_20191110_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='exam',
        ),
        migrations.AddField(
            model_name='question',
            name='question',
            field=models.CharField(choices=[('V_OR_F', 'V_OR_F'), ('MULTIPLE_CHOICES', 'MULTIPLE_CHOICES'), ('SHOT', 'SHOT'), ('SCRATCH_CARD', 'SCRATCH_CARD')], default='MULTIPLE_CHOICES', help_text='Tipos de questão que podem ser criadas.', max_length=20, verbose_name='Tipo de questão'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('EXERCISE', 'EXERCISE'), ('TRADITIONAL', 'TRADITIONAL'), ('TBL', 'TBL')], default='EXERCISE', help_text='Verificar o tipo de avaliação que a questão irá fazer parte.', max_length=30, verbose_name='Tipo de avaliação'),
        ),
    ]
