# Generated by Django 2.1.4 on 2019-11-10 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_auto_20191110_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(choices=[('V_OR_F', 'V_OR_F'), ('MULTIPLE_CHOICES', 'MULTIPLE_CHOICES'), ('SHOT', 'SHOT')], default='MULTIPLE_CHOICES', help_text='Tipos de questão que podem ser criadas.', max_length=20, verbose_name='Tipo de questão'),
        ),
    ]
