# Generated by Django 2.1.4 on 2019-10-20 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disciplines', '0007_remove_discipline_was_group_provided'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data na qual o objeto foi criado.', verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data na qual o objeto foi atualizado.', verbose_name='Atualizado em')),
                ('title', models.CharField(help_text='Título da seção', max_length=100, verbose_name='Título')),
                ('description', models.TextField(help_text='Descrição da seção', verbose_name='Descrição')),
                ('is_closed', models.BooleanField(default=True, help_text='Verifica se a seção da disciplina está fechada.', verbose_name='Está Fechada?')),
                ('is_finished', models.BooleanField(default=False, help_text='Verifica se a seção da disciplina foi finalizada.', verbose_name='Foi finalizada')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='disciplines.Discipline', verbose_name='Disciplina')),
            ],
            options={
                'db_table': 'sections',
                'ordering': ['title', 'created_at'],
            },
        ),
    ]
