# Generated by Django 2.1.4 on 2019-09-21 20:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplines', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discipline',
            options={'ordering': ['title', 'created_at']},
        ),
        migrations.AlterField(
            model_name='discipline',
            name='monitors_limit',
            field=models.PositiveIntegerField(default=0, help_text='Monitors limit to insert in the class.', validators=[django.core.validators.MaxValueValidator(15, 'There can be no more than %(limit_value)s monitors in the class.'), django.core.validators.MinValueValidator(0, 'Ensure this value is greater than or equal to %(limit_value)s.')], verbose_name='Monitors limit'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='students_limit',
            field=models.PositiveIntegerField(default=0, help_text='Students limit to get in the class.', validators=[django.core.validators.MaxValueValidator(150, 'There can be no more than %(limit_value)s students in the class.'), django.core.validators.MinValueValidator(5, 'Must have at least %(limit_value)s students in class.')], verbose_name='Students limit'),
        ),
        migrations.AlterModelTable(
            name='discipline',
            table='disciplines',
        ),
    ]
