# Generated by Django 2.1.4 on 2019-09-28 05:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disciplines', '0003_auto_20190925_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='classroom',
            field=models.CharField(help_text='Turma da disciplina.', max_length=20, verbose_name='Sala'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='course',
            field=models.CharField(blank=True, help_text='Curso que é ministrado a disciplina.', max_length=100, verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Data na qual o objeto foi criado.', verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='description',
            field=models.TextField(help_text='Ementa da disciplina.', verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='institution',
            field=models.CharField(blank=True, help_text='Universidade ou escola em que o usuário está inserido.', max_length=100, verbose_name='Instituição'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='is_closed',
            field=models.BooleanField(default=False, help_text='Verifica se a disciplina está fechada.', verbose_name='Está fechada?'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='monitors',
            field=models.ManyToManyField(blank=True, related_name='monitor_classes', to=settings.AUTH_USER_MODEL, verbose_name='Monitores'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='monitors_limit',
            field=models.PositiveIntegerField(default=0, help_text='Limite de monitores para entrar na turma.', validators=[django.core.validators.MaxValueValidator(15, 'There can be no more than %(limit_value)s monitors in the class.'), django.core.validators.MinValueValidator(0, 'Ensure this value is greater than or equal to %(limit_value)s.')], verbose_name='Limite de monitores'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='password',
            field=models.CharField(blank=True, help_text='Senha para entrar na disciplina.', max_length=30, verbose_name='Senha'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='student_classes', to=settings.AUTH_USER_MODEL, verbose_name='Alunos'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='students_limit',
            field=models.PositiveIntegerField(default=0, help_text='Limite de estudantes para entrar na turma.', validators=[django.core.validators.MaxValueValidator(150, 'There can be no more than %(limit_value)s students in the class.'), django.core.validators.MinValueValidator(5, 'Must have at least %(limit_value)s students in class.')], verbose_name='Limite de estudantes.'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplines', to=settings.AUTH_USER_MODEL, verbose_name='Professor'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='title',
            field=models.CharField(help_text='Título da disciplina', max_length=100, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Data na qual o objeto foi atualizado.', verbose_name='Atualizado em'),
        ),
    ]
