# Generated by Django 2.1.4 on 2019-10-10 04:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplines', '0004_auto_20190928_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='course',
            field=models.CharField(blank=True, help_text='Curso que é ministrado a disciplina.', max_length=50, verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='institution',
            field=models.CharField(blank=True, help_text='Universidade ou escola em que o usuário está inserido.', max_length=50, verbose_name='Instituição'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='students_limit',
            field=models.PositiveIntegerField(default=5, help_text='Limite de estudantes para entrar na turma.', validators=[django.core.validators.MaxValueValidator(150, 'There can be no more than %(limit_value)s students in the class.'), django.core.validators.MinValueValidator(5, 'Must have at least %(limit_value)s students in class.')], verbose_name='Limite de estudantes.'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='title',
            field=models.CharField(help_text='Título da disciplina', max_length=50, verbose_name='Título'),
        ),
    ]
