# Generated by Django 2.1.4 on 2019-11-03 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disciplines', '0007_remove_discipline_was_group_provided'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='discipline',
            table='alma_disciplines',
        ),
    ]
