# Generated by Django 2.1.4 on 2019-11-10 02:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplines', '0009_auto_20191103_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='monitors_limit',
            field=models.PositiveIntegerField(default=0, help_text='Limite de monitores para entrar na turma.', validators=[django.core.validators.MaxValueValidator(15, 'Não deve haver mais que %(limit_value)s monitores na turma.'), django.core.validators.MinValueValidator(0, 'Tenha certeza que o valor é maior ou igual a %(limit_value)s')], verbose_name='Limite de monitores'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='students_limit',
            field=models.PositiveIntegerField(default=5, help_text='Limite de estudantes para entrar na turma.', validators=[django.core.validators.MaxValueValidator(150, 'Não deve haver mais que %(limit_value)s estudantes na turma.'), django.core.validators.MinValueValidator(5, 'Deve ter no mínimo %(limit_value)s estudantes na turma.')], verbose_name='Limite de estudantes.'),
        ),
    ]
