# Generated by Django 2.1.4 on 2019-10-26 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='alternative_A',
            field=models.TextField(blank=True, help_text='Descrição da alternativa A', verbose_name='Alternativa A'),
        ),
        migrations.AlterField(
            model_name='question',
            name='alternative_B',
            field=models.TextField(blank=True, help_text='Descrição da alternativa B', verbose_name='Alternativa B'),
        ),
        migrations.AlterField(
            model_name='question',
            name='alternative_C',
            field=models.TextField(blank=True, help_text='Descrição da alternativa C', verbose_name='Alternativa C'),
        ),
        migrations.AlterField(
            model_name='question',
            name='alternative_D',
            field=models.TextField(blank=True, help_text='Descrição da alternativa D', verbose_name='Alternativa D'),
        ),
    ]
