# Generated by Django 2.1.4 on 2019-10-27 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20191026_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alternative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data na qual o objeto foi criado.', verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data na qual o objeto foi atualizado.', verbose_name='Atualizado em')),
                ('title', models.TextField(blank=True, help_text='Título da alternativa', verbose_name='Título')),
                ('is_correct', models.BooleanField(default=False, help_text='Verifica se essa alternativa é a correta.', verbose_name='É a alternativa correta?')),
            ],
            options={
                'db_table': 'alternatives',
                'ordering': ['created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='question',
            name='alternative_A',
        ),
        migrations.RemoveField(
            model_name='question',
            name='alternative_B',
        ),
        migrations.RemoveField(
            model_name='question',
            name='alternative_C',
        ),
        migrations.RemoveField(
            model_name='question',
            name='alternative_D',
        ),
        migrations.RemoveField(
            model_name='question',
            name='correct_answer',
        ),
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.TextField(blank=True, help_text='Descrição da seção', verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('V_OR_F', 'V_OR_F'), ('MULTIPLE_CHOICES', 'MULTIPLE_CHOICES'), ('SHOT', 'SHOT'), ('SCRATCH_CARD', 'SCRATCH_CARD')], default='MULTIPLE_CHOICES', help_text='Tipos de questão que podem ser criadas.', max_length=20, verbose_name='Tipo de questão'),
        ),
        migrations.AlterModelTable(
            name='question',
            table='questions',
        ),
        migrations.AddField(
            model_name='alternative',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternatives', to='questions.Question'),
        ),
    ]
