# Generated by Django 2.1.4 on 2019-11-16 21:13

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sections', '0003_section_methodology'),
        ('alma_accounts', '0002_auto_20191103_0340'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data na qual o objeto foi criado.', verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data na qual o objeto foi atualizado.', verbose_name='Atualizado em')),
                ('answers', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Respostas da avaliação.')),
                ('score', models.PositiveIntegerField(default=0, help_text='Pontuação da avaliação', verbose_name='Pontuação')),
                ('exam', models.CharField(choices=[('EXERCISE', 'EXERCISE'), ('GAMIFICATION', 'GAMIFICATION'), ('TRADITIONAL', 'TRADITIONAL'), ('IRAT', 'IRAT'), ('GRAT', 'GRAT'), ('PEER_REVIEW', 'PEER_REVIEW')], default='EXERCISE', help_text='Tipo de avalição ativa que pertence a submissão.', max_length=50, verbose_name='Tipo de avaliação')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='sections.Section', verbose_name='Submissão')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='alma_accounts.AlmaUser', verbose_name='Estudante')),
            ],
            options={
                'db_table': 'alma_submissions',
                'ordering': ['created_at'],
            },
        ),
    ]
