# Generated by Django 2.1.4 on 2019-11-17 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='grade',
            field=models.PositiveIntegerField(default=0, help_text='Nota final', verbose_name='Nota'),
        ),
        migrations.AddField(
            model_name='submission',
            name='qtd',
            field=models.PositiveIntegerField(default=0, help_text='Quantidade total de pontos', verbose_name='Quantidade total'),
        ),
    ]
