# Generated by Django 2.1.4 on 2019-11-17 01:22

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_auto_20191116_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='answers_test',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, verbose_name='Gabarito da avaliação.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submission',
            name='answers',
            field=django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Respostas do estudante.'),
        ),
    ]
