# Generated by Django 2.1.4 on 2019-11-17 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_auto_20191116_2222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='answers_test',
            new_name='correct_answers',
        ),
    ]
