# Generated by Django 2.1.4 on 2019-11-03 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alma_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='almauser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='alma_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
