# Generated by Django 2.1.4 on 2019-09-30 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190928_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='identifier',
            field=models.CharField(default=130136484, help_text='Identificador dentro de sua universidade', max_length=50, verbose_name='Mátricula'),
            preserve_default=False,
        ),
    ]
