# Generated by Django 2.1.4 on 2019-10-02 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_passwordreset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='Confirmado?'),
        ),
    ]
