# Generated by Django 2.1.4 on 2019-11-03 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20191014_0130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='identifier',
        ),
        migrations.RemoveField(
            model_name='user',
            name='permission',
        ),
        migrations.RemoveField(
            model_name='user',
            name='photo',
        ),
    ]
