# TESTS --------------------------------------------------------
folder := pgtbl

test: coverage report xml

coverage:
	# Execute all tests
	coverage run --source="." project/manage.py test ${folder}

report:
	# Show coverage on terminal
	coverage report -m

html:
	# Generate coverage html
	coverage html

xml:
	# Generate coverage xml
	coverage xml

clean:
	# Remove the html generated by coverage
	rm -rf ./htmlcov/