# Generated by Django 2.1.4 on 2019-10-17 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplines', '0005_auto_20191010_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='was_group_provided',
            field=models.BooleanField(default=False, help_text='Liberar o grupo para visualização', verbose_name='Liberar o grupo'),
        ),
    ]
